# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  scheme: 'Unity-iPhone'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ios_cert.p12'
    certPwd: 'qwerty'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ios_test.mobileprovision'
    removeProfile: false

- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
    packageApp: true
    archivePath: iOSBuild
    exportPath: $(Build.ArtifactStagingDirectory)/ios
    signingOption: 'manual'
    signingIdentity: <Code Sign Identity>
    provisioningProfileUuid: 57e5a5b3-0c79-4de6-9968-4eda7f6bf9ba
    provisioningProfileName: ios_test.mobileprovision
    # args: 'PROVISIONING_PROFILE_APP=<ProvisioningProfileUuid> PROVISIONING_PROFILE_SPECIFIER_APP=<ProvisioningProfileName>'
    useXcpretty: false
